__global_actions:
  import_configs:
    - core.entity_view_display.node.faq.teaser_unified
    - core.entity_view_display.taxonomy_term.faq_category.teaser_unified

field.field.node.faq.field_content_paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            teaser_wrapper: teaser_wrapper
