core.entity_view_display.node.faq.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        body:
          weight: 1
        field_content_paragraphs:
          weight: 2
        field_detailed_question:
          weight: 0
        field_faq_category:
          weight: 3
      third_party_settings:
        field_group:
          group_interact:
            weight: 4
core.entity_view_display.taxonomy_term.faq_category.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
      third_party_settings:
        field_group:
          group_interact:
            weight: 3
          group_related_questions:
            weight: 2
          group_sub_categories:
            weight: 1
