openculturas_base.settings:
  type: theme_settings
  label: 'OpenCulturas base theme settings'
  mapping:
    background_image:
      type: mapping
      label: 'Background image settings'
      mapping:
        mode:
         type: string
        path:
          label: 'Path to background image'
          type: uri
