# Schema for the configuration files of the OpenCulturas Base theme.
openculturas_base.settings:
  type: theme_settings
  label: 'OpenCulturas Base settings'
  mapping:
    color-primary:
      type: string
      label: Primary color
    color-primary-dark:
      type: string
      label: Primary Dark color
    color-danger:
      type: string
      label: Danger color
    color-success:
      type: string
      label: Success color
    color-warning:
      type: string
      label: Warning color
    color-complete:
      type: string
      label: Complete color
    color-info:
      type: string
      label: Info color
    color-neutral-canvas:
      type: string
      label: Neutral canvas color
    color-white:
      type: string
      label: White color
    color-black:
      type: string
      label: Black color
    color-divider:
      type: string
      label: Divider bar color
    color-neutral-10:
      type: string
      label: Neutral grey 10 color
    color-neutral-20:
      type: string
      label: Neutral grey 20 color
    color-neutral-30:
      type: string
      label: Neutral grey 30 color
    color-neutral-40:
      type: string
      label: Neutral grey 40 color
    color-neutral-50:
      type: string
      label: Neutral grey 50 color
    color-neutral-60:
      type: string
      label: Neutral grey 60 color

