field.formatter.settings.swiffy_slider:
  type: mapping
  label: Swiffy Slider formatter settings
  mapping:
    view_mode:
      type: string
      label: View mode
    swiffy_slider_permalink:
      type: uri
      label: Perma link
