include:
  - project: 'devops/gitlab-ci-templates'
    ref: 1.2.10
    file:
      - 'drupal.yml'

variables:
  CLOUDRON_DB_SOURCE: 'gitrepo'

default:
  image: docker:23.0-git@sha256:f08f6eae32a7b2d7f5411e2d3197d073d5414660c76a4c6d5a5ada66657f8198

build:image:stage:
  extends: .build:image:stage

deploy:stage:
  extends: .deploy_cloudron:stage
  needs:
    - build:image:stage
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: "$CI_COMMIT_REF_NAME == $PRELIVE_BRANCH_NAME"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual

deploy:stage:remove:
  extends: .deploy_cloudron:stage:remove
  needs:
    - deploy:stage

build:image:prelive:
  extends: .build:image:prelive

deploy:prelive:
  extends: .deploy_cloudron:prelive
  needs:
    - build:image:prelive

database:snapshot:
  extends: .pre_cloudron
  stage: cronjobs
  variables:
    APP_ENV: stage
  script:
    - bash ${DEBUG:+-o xtrace} /ci/cloudron/db_snapshot.sh
  rules:
    - if: $DB_CREATE_SNAPSHOT

test create project:
  image: $CLOUDRON_BASE_IMAGE
  stage: test
  variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer"
    COMPOSER_EXIT_ON_PATCH_FAILURE: 1
    COMPOSER_MEMORY_LIMIT: -1
  cache:
    key: composer
    paths:
      - $COMPOSER_CACHE_DIR
    when: always
  script:
    - composer create-project --remove-vcs --no-interaction --ansi drupal/openculturas_project example.org
    - cd example.org
    - composer audit --locked --no-interaction --ansi
    - composer update --prefer-lowest --no-interaction --ansi
  # Enable when https://www.drupal.org/project/smtp/issues/3352909 is fixed.
  #  - composer audit --locked --no-interaction --ansi
  rules:
    - if: $TEST_COMPOSER_CREATE_PROJECT
