views.view.related_location:
  expected_config: { }
  update_actions:
    delete:
      display:
        by_location_type:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        by_location_type:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
    change:
      display:
        by_location_type:
          display_title: 'By location type'
