workflows.workflow.draften:
  expected_config: {  }
  update_actions:
    add:
      type_settings:
        transitions:
          unpublish:
            from:
              - draft
workflows.workflow.draften_member:
  expected_config: {  }
  update_actions:
    add:
      type_settings:
        transitions:
          unpublish:
            from:
              - draft
workflows.workflow.magazine_article:
  expected_config: {  }
  update_actions:
    add:
      type_settings:
        transitions:
          unpublish:
            from:
              - draft
