views.view.my_content:
  expected_config:
    display:
      my_content_block:
        display_options:
          filters:
            type_1:
              expose:
                reduce: false
              value: {  }
  update_actions:
    change:
      display:
        my_content_block:
          display_options:
            filters:
              type_1:
                expose:
                  reduce: true
                value:
                  article: article
                  date: date
                  event: event
                  page: page
