__global_actions:
  import_configs:
    - field.storage.node.field_sub_type
    - field.field.node.page.field_sub_type
    - field.field.node.location.field_sub_type
    - field.field.node.article.field_sub_type
    - field.field.node.event.field_sub_type
