core.entity_view_display.node.article.search_index:
  expected_config:
    hidden:
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          label: hidden
          region: content
          settings:
            link: false
          third_party_settings:
            field_formatter_class:
              class: ''
          type: entity_reference_label
          weight: 0
core.entity_view_display.node.event.search_index:
  expected_config:
    hidden:
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          label: hidden
          region: content
          settings:
            link: false
          third_party_settings:
            field_formatter_class:
              class: ''
          type: entity_reference_label
          weight: 0
core.entity_view_display.node.location.search_index:
  expected_config:
    hidden:
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          label: hidden
          region: content
          settings:
            link: false
          third_party_settings:
            field_formatter_class:
              class: ''
          type: entity_reference_label
          weight: 0
core.entity_view_display.node.page.search_index:
  expected_config:
    hidden:
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          label: hidden
          region: content
          settings:
            link: false
          third_party_settings:
            field_formatter_class:
              class: ''
          type: entity_reference_label
          weight: 0
