__global_actions:
  install_modules:
    - paragraphs_type_permissions

user.role.anonymous:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view paragraph content accessibility'
        - 'view paragraph content address_data'
        - 'view paragraph content block'
        - 'view paragraph content bookable_event'
        - 'view paragraph content contact_data'
        - 'view paragraph content download'
        - 'view paragraph content gallery'
        - 'view paragraph content media'
        - 'view paragraph content media_mention'
        - 'view paragraph content member'
        - 'view paragraph content text'
        - 'view paragraph content view'

user.role.authenticated:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view paragraph content accessibility'
        - 'view paragraph content address_data'
        - 'view paragraph content block'
        - 'view paragraph content bookable_event'
        - 'view paragraph content contact_data'
        - 'view paragraph content download'
        - 'view paragraph content gallery'
        - 'view paragraph content media'
        - 'view paragraph content media_mention'
        - 'view paragraph content member'
        - 'view paragraph content text'
        - 'view paragraph content view'
        - 'create paragraph content accessibility'
        - 'create paragraph content address_data'
        - 'create paragraph content bookable_event'
        - 'create paragraph content contact_data'
        - 'create paragraph content download'
        - 'create paragraph content gallery'
        - 'create paragraph content media'
        - 'create paragraph content media_mention'
        - 'create paragraph content member'
        - 'create paragraph content text'
        - 'update paragraph content accessibility'
        - 'update paragraph content address_data'
        - 'update paragraph content bookable_event'
        - 'update paragraph content contact_data'
        - 'update paragraph content download'
        - 'update paragraph content gallery'
        - 'update paragraph content media'
        - 'update paragraph content media_mention'
        - 'update paragraph content member'
        - 'update paragraph content text'
        - 'delete paragraph content accessibility'
        - 'delete paragraph content address_data'
        - 'delete paragraph content bookable_event'
        - 'delete paragraph content contact_data'
        - 'delete paragraph content download'
        - 'delete paragraph content gallery'
        - 'delete paragraph content media'
        - 'delete paragraph content media_mention'
        - 'delete paragraph content member'
        - 'delete paragraph content text'

user.role.magazine_editor:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create paragraph content block'
        - 'update paragraph content block'
        - 'delete paragraph content block'
        - 'edit behavior plugin settings'

user.role.oc_admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'bypass paragraphs type content access'
        - 'edit behavior plugin settings'
