views.view.related_date:
  expected_config: { }
  update_actions:
    change:
      display:
        block_front_dates:
          display_options:
            filters:
              title:
                expose:
                  autocomplete_raw_suggestion: 0
                  autocomplete_raw_dropdown: 0
              title_1:
                expose:
                  autocomplete_raw_suggestion: 0
                  autocomplete_raw_dropdown: 0
        upcoming_dates:
          display_options:
            filters:
              title:
                expose:
                  autocomplete_raw_suggestion: 0
                  autocomplete_raw_dropdown: 0
              title_1:
                expose:
                  autocomplete_raw_suggestion: 0
                  autocomplete_raw_dropdown: 0

