filter.format.advanced_html:
  expected_config:
    filters:
      filter_html:
        settings:
          allowed_html: '<em> <strong> <cite> <blockquote cite> <code> <ul type> <ol type start> <li> <dl> <dt> <dd> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <a href hreflang data-entity-substitution data-entity-type data-entity-uuid title> <s> <sup> <sub> <span dir lang> <drupal-media data-entity-type data-entity-uuid data-view-mode data-align data-caption alt title>'
    weight: -7
  update_actions:
    change:
      filters:
        filter_html:
          settings:
            allowed_html: '<em> <strong> <cite> <blockquote cite> <code> <ul type> <ol type start> <li> <dl> <dt> <dd> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <a href hreflang data-entity-substitution data-entity-type data-entity-uuid title> <s> <sup> <sub> <span dir lang> <drupal-media data-entity-type data-entity-uuid data-view-mode data-align data-caption alt title> <p>'
      weight: -10
