__global_actions:
  import_configs:
    - core.entity_view_display.node.article.teaser_unified
    - core.entity_view_display.node.date.teaser_unified
    - core.entity_view_display.node.event.teaser_unified
    - core.entity_view_display.node.location.teaser_unified
    - core.entity_view_display.node.page.teaser_unified
    - core.entity_view_display.node.profile.teaser_unified
    - core.entity_view_display.taxonomy_term.category.teaser_unified
    - core.entity_view_display.taxonomy_term.column.teaser_unified
