core.entity_view_display.user.user.full:
  expected_config:
    content:
      field_my_content_view_ref:
        settings:
          always_build_output: false
        third_party_settings: {  }
  update_actions:
    change:
      content:
        field_my_content_view_ref:
          settings:
            always_build_output: true
          third_party_settings:
            field_formatter_class:
              class: ''
