core.entity_view_display.taxonomy_term.event_type.full:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_events:
            children:
              - field_related_event_view_ref
            format_settings:
              classes: ''
              description: ''
              id: ''
              open: true
              required_fields: false
              show_empty_fields: false
            format_type: details
            label: Events
            parent_name: ''
            region: content
            weight: 3
    change:
      content:
        field_related_event_view_ref:
          weight: 4
      third_party_settings:
        field_group:
          group_sub_catgories:
            label: Sub-categories
core.entity_view_display.taxonomy_term.location_type.full:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_locations:
            children:
              - field_related_location_view_ref
            format_settings:
              classes: ''
              description: ''
              id: ''
              open: true
              required_fields: false
              show_empty_fields: false
            format_type: details
            label: Locations
            parent_name: ''
            region: content
            weight: 3
    change:
      content:
        field_related_location_view_ref:
          weight: 4
