views.view.related_date:
  expected_config:
    display:
      upcoming_dates_map:
        display_options:
          style:
            options:
              grouping:
                -
                  field: title
                  overlays_options:
                    disabled_overlays: {  }
                    hidden_overlays_controls: {  }
                  rendered: true
  update_actions:
    delete:
      display:
        upcoming_dates_map:
          display_options:
            style:
              options:
                grouping:
    change:
      display:
        upcoming_dates_map:
          display_options:
            style:
              options:
                grouping: {  }
