views.view.related_date:
  expected_config: { }
  update_actions:
    add:
      display:
        by_term:
          id: by_term
          display_title: 'By term'
          display_plugin: block
          position: 9
          display_options:
            arguments:
              field_category_target_id:
                id: field_category_target_id
                table: node__field_category
                field: field_category_target_id
                relationship: field_event_description
                group_type: group
                admin_label: ''
                plugin_id: numeric
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: taxonomy_tid
                default_argument_options:
                  term_page: '1'
                  node: false
                  limit: false
                  vids: { }
                  anyall: ','
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: true
                validate:
                  type: 'entity:taxonomy_term'
                  fail: 'not found'
                validate_options:
                  bundles:
                    category: category
                  access: false
                  operation: view
                  multiple: 0
                break_phrase: false
                not: false
            defaults:
              arguments: false
            display_description: ''
            rendering_language: '***LANGUAGE_language_interface***'
            display_extenders: { }
          cache_metadata:
            max-age: -1
            contexts:
              - 'languages:language_interface'
              - url
              - url.query_args
              - 'user.node_grants:view'
              - user.permissions
            tags:
              - 'config:field.storage.node.body'
              - 'config:field.storage.node.field_address_data'
              - 'config:field.storage.node.field_attendance_mode'
              - 'config:field.storage.node.field_date'
              - 'config:field.storage.node.field_event_status'
              - 'config:field.storage.node.field_mood_image'
              - 'config:field.storage.node.field_premiere'
              - 'config:field.storage.node.field_subtitle'
