core.entity_form_display.node.article.default:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_meta_information:
            children:
              - field_column
              - field_category
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          type: options_select
          weight: 12
          region: content
          settings: { }
          third_party_settings: { }
      third_party_settings:
        field_group:
          group_meta_information:
            children:
              - group_tags_wrapper
          group_tags_wrapper:
            children:
              - field_column
              - field_sub_type
              - field_category
            label: 'Tags wrapper'
            region: content
            parent_name: group_meta_information
            weight: 10
            format_type: html_element
            format_settings:
              classes: tags-wrapper
              show_empty_fields: false
              id: ''
              element: div
              show_label: false
              label_element: h3
              label_element_classes: ''
              attributes: ''
              effect: none
              speed: fast
              required_fields: true

core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_event_tab_basics:
            children:
              - field_category
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          type: options_select
          weight: 24
          region: content
          settings: { }
          third_party_settings: { }
      third_party_settings:
        field_group:
          group_event_tab_basics:
            children:
              - group_tags_wrapper
          group_tags_wrapper:
            children:
              - field_sub_type
              - field_category
            label: 'Tags wrapper'
            region: content
            parent_name: group_event_tab_basics
            weight: 23
            format_type: html_element
            format_settings:
              classes: tags-wrapper
              show_empty_fields: false
              id: ''
              element: div
              show_label: false
              label_element: h3
              label_element_classes: ''
              attributes: ''
              effect: none
              speed: fast
              required_fields: true

core.entity_form_display.node.location.default:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_about:
            children:
              - field_category
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          type: options_select
          weight: 14
          region: content
          settings: { }
          third_party_settings: { }
      third_party_settings:
        field_group:
          group_about:
            children:
              - group_tags_wrapper
          group_tags_wrapper:
            children:
              - field_sub_type
              - field_category
            label: 'Tags wrapper'
            region: content
            parent_name: group_about
            weight: 3
            format_type: html_element
            format_settings:
              classes: tags-wrapper
              show_empty_fields: false
              id: ''
              element: div
              show_label: false
              label_element: h3
              label_element_classes: ''
              attributes: ''
              effect: none
              speed: fast
              required_fields: true


core.entity_form_display.node.page.default:
  expected_config: { }
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      third_party_settings:
        field_group:
          group_administrative:
            children:
              - field_sub_type
      content:
        field_sub_type:
          type: options_select
          weight: 7
          region: content
          settings: { }
          third_party_settings: { }
