field.field.paragraph.contact_data.field_social_media_links:
  expected_config: {  }
  update_actions:
    add:
      settings:
        platforms:
          mastodon:
            description: ''
            enabled: true
