core.entity_form_display.node.article.bulk_edit:
  expected_config:
    hidden:
      field_category: true
      field_column: true
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_category: true
        field_column: true
        field_sub_type: true
      third_party_settings:
        field_group:
    add:
      content:
        field_category:
          region: content
          settings:
            match_limit: 10
            match_operator: CONTAINS
            placeholder: ''
            size: 60
          third_party_settings: {  }
          type: entity_reference_autocomplete
          weight: 0
        field_column:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_select
          weight: 0
        field_sub_type:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 0

core.entity_form_display.node.event.bulk_edit:
  expected_config:
    hidden:
      field_category: true
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_category: true
        field_sub_type: true
      third_party_settings:
        field_group:
    add:
      content:
        field_category:
          region: content
          settings:
            match_limit: 10
            match_operator: CONTAINS
            placeholder: ''
            size: 60
          third_party_settings: {  }
          type: entity_reference_autocomplete
          weight: 0
        field_sub_type:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 0

core.entity_form_display.node.location.bulk_edit:
  expected_config:
    hidden:
      field_category: true
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_category: true
        field_sub_type: true
      third_party_settings:
        field_group:
    add:
      content:
        field_category:
          region: content
          settings:
            match_limit: 10
            match_operator: CONTAINS
            placeholder: ''
            size: 60
          third_party_settings: {  }
          type: entity_reference_autocomplete
          weight: 0
        field_sub_type:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 0

core.entity_form_display.node.page.bulk_edit:
  expected_config:
    hidden:
      field_sub_type: true
  update_actions:
    delete:
      hidden:
        field_sub_type: true
    add:
      content:
        field_sub_type:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 0

core.entity_form_display.node.profile.bulk_edit:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:

core.entity_form_display.node.date.bulk_edit:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:
