__global_actions:
  install_modules:
    - openculturas_teaser
  import_configs:
    - paragraphs.paragraphs_type.teaser_external
    - paragraphs.paragraphs_type.teaser_node
    - paragraphs.paragraphs_type.teaser_term
    - paragraphs.paragraphs_type.teaser_wrapper
    - core.entity_view_mode.paragraph.grid
    - core.entity_view_mode.paragraph.slider
    - field.storage.paragraph.field_teasers
    - field.storage.paragraph.field_url_single_value
    - field.storage.paragraph.field_article
    - field.storage.paragraph.field_term
    - field.field.paragraph.teaser_external.field_url_single_value
    - field.field.paragraph.teaser_node.field_article
    - field.field.paragraph.teaser_term.field_term
    - field.field.paragraph.teaser_wrapper.field_teasers
    - field.field.paragraph.teaser_wrapper.paragraph_view_mode
    - core.entity_form_display.paragraph.teaser_external.default
    - core.entity_form_display.paragraph.teaser_node.default
    - core.entity_form_display.paragraph.teaser_term.default
    - core.entity_form_display.paragraph.teaser_wrapper.default
    - core.entity_view_display.paragraph.teaser_external.default
    - core.entity_view_display.paragraph.teaser_node.default
    - core.entity_view_display.paragraph.teaser_term.default
    - core.entity_view_display.paragraph.teaser_wrapper.default
    - core.entity_view_display.paragraph.teaser_wrapper.grid
    - core.entity_view_display.paragraph.teaser_wrapper.slider

user.role.anonymous:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view paragraph content teaser_external'
        - 'view paragraph content teaser_node'
        - 'view paragraph content teaser_term'
        - 'view paragraph content teaser_wrapper'
user.role.authenticated:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view paragraph content teaser_external'
        - 'view paragraph content teaser_node'
        - 'view paragraph content teaser_term'
        - 'view paragraph content teaser_wrapper'
user.role.magazine_editor:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create paragraph content teaser_external'
        - 'create paragraph content teaser_node'
        - 'create paragraph content teaser_term'
        - 'create paragraph content teaser_wrapper'
        - 'delete paragraph content teaser_external'
        - 'delete paragraph content teaser_node'
        - 'delete paragraph content teaser_term'
        - 'delete paragraph content teaser_wrapper'
        - 'update paragraph content teaser_external'
        - 'update paragraph content teaser_node'
        - 'update paragraph content teaser_term'
        - 'update paragraph content teaser_wrapper'

field.field.node.article.field_content_paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            teaser_wrapper: teaser_wrapper

field.field.node.page.field_content_paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            teaser_wrapper: teaser_wrapper
