views.view.related_pages:
  expected_config: { }
  update_actions:
    delete:
      display:
        by_author:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        by_page_type:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        default:
          cache_metadata:
            contexts:
              - 'languages:language_content'
          display_options:
            filters:
              langcode:
        mention_by_article:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        related_article_latest:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        by_author:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        by_page_type:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        default:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        related_article_latest:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
    change:
      description: 'OpenCulturas: list of related pages'
      display:
        by_author:
          position: 4
        by_page_type:
          display_title: 'By page type - on term page'
        default:
          display_options:
            empty:
              area:
                content:
                  value: 'Currently no pages relate to this content.'
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
        mention_by_article:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
            title: ''
            defaults:
              filters: true
              filter_groups: true
          display_title: 'Mentioned by'
          position: 3
        related_article_latest:
          position: 1
      label: 'Related pages'
