views.view.related_article:
  expected_config: { }
  update_actions:
    delete:
      display:
        block_1:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        block_1:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
    change:
      display:
        block_1:
          display_title: 'By article type - on term page'
          position: 6
