
views.view.frontpage:
  expected_config:  {  }
  update_actions:
    delete:
      display:
        block_front_all:
          display_options:
            filters:
              langcode:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        block_front_articles_x:
          display_options:
            filters:
              langcode:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        block_front_events:
          display_options:
            filters:
              langcode:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        block_front_locations:
          display_options:
            filters:
              langcode:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        block_front_profiles:
          display_options:
            filters:
              langcode:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        block_front_all:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'
        block_front_articles_x:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: default_langcode
                  label: 'Default translation'
                  multiple: false
                  operator: default_langcode_op
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'
        block_front_events:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'
        block_front_locations:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'
        block_front_profiles:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'

