block.block.bookmarkflagicon:
  expected_config: {  }
  update_actions:
    change:
      status: true
      region: header_intro

flag.flag.recommendation_node:
  expected_config: {  }
  update_actions:
    change:
      unflag_short: 'Edit recommendation'
      unflag_long: 'Modify or remove'
