__global_actions:
  install_modules:
    - eca_base
    - eca_content
    - eca_flag
    - eca_language
    - eca_user
    - eca_workflow
  import_configs:
    - eca.eca.process_fhzwp6n
    - eca.eca.process_gfgdois
    - eca.eca.process_xutbysi
    - eca.model.process_fhzwp6n
    - eca.model.process_gfgdois
    - eca.model.process_xutbysi
user.role.oc_admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'administer eca_notification_recipient'
