views.view.moderated_content:
  expected_config:
    display:
      default:
        display_options:
          fields:
            name:
              exclude: false
  update_actions:
    add:
      display:
        default:
          display_options:
            fields:
              revision_uid:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: target_id
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: false
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_field: revision_uid
                entity_type: node
                exclude: false
                field: revision_uid
                field_api_classes: false
                group_column: target_id
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: revision_uid
                label: 'last edit by'
                multi_type: separator
                plugin_id: field
                relationship: nid
                separator: ', '
                settings:
                  link: true
                table: node_revision
                type: entity_reference_label
            style:
              options:
                columns:
                  revision_uid: revision_uid
                  views_bulk_operations_bulk_form: views_bulk_operations_bulk_form
                info:
                  revision_uid:
                    align: ''
                    default_sort_order: asc
                    empty_column: false
                    responsive: ''
                    separator: ''
                    sortable: false
                  views_bulk_operations_bulk_form:
                    align: ''
                    empty_column: false
                    responsive: ''
                    separator: ''
    change:
      display:
        default:
          display_options:
            fields:
              name:
                exclude: true
