views.view.entity_reference_node:
  expected_config:
    display:
      default:
        display_options:
          filters:
            status:
              entity_field: status
              entity_type: node
              expose:
                operator: ''
                operator_limit_selection: false
                operator_list: {  }
              field: status
              group: 1
              id: status
              plugin_id: boolean
              table: node_field_data
              value: '1'
      er_organizer:
        display_options:
          filters:
            status:
              entity_field: status
              entity_type: node
              expose:
                operator: ''
                operator_limit_selection: false
                operator_list: {  }
              field: status
              group: 1
              id: status
              plugin_id: boolean
              table: node_field_data
              value: '1'
            status_1:
              admin_label: ''
              entity_field: status
              entity_type: node
              expose:
                description: ''
                identifier: ''
                label: ''
                multiple: false
                operator: ''
                operator_id: ''
                operator_limit_selection: false
                operator_list: {  }
                remember: false
                remember_roles:
                  authenticated: authenticated
                required: false
                use_operator: false
              exposed: false
              field: status
              group: 2
              group_info:
                default_group: All
                default_group_multiple: {  }
                description: ''
                group_items: {  }
                identifier: ''
                label: ''
                multiple: false
                optional: true
                remember: false
                widget: select
              group_type: group
              id: status_1
              is_grouped: false
              operator: '='
              plugin_id: boolean
              relationship: none
              table: node_field_data
              value: '1'
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              status:
        er_organizer:
          display_options:
            filters:
              status:
              status_1:
    add:
      display:
        default:
          cache_metadata:
            contexts:
              - user
        er_organizer:
          cache_metadata:
            contexts:
              - user
    change:
      display:
        default:
          display_options:
            filters:
              status_extra:
                admin_label: ''
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: status_extra
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: status_extra
                is_grouped: false
                operator: '='
                plugin_id: node_status
                relationship: none
                table: node_field_data
                value: false
        er_organizer:
          display_options:
            filters:
              status_extra:
                admin_label: ''
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: status_extra
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: status_extra
                is_grouped: false
                operator: '='
                plugin_id: node_status
                relationship: none
                table: node_field_data
                value: false
              status_extra_1:
                admin_label: ''
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: status_extra
                group: 2
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: status_extra_1
                is_grouped: false
                operator: '='
                plugin_id: node_status
                relationship: none
                table: node_field_data
                value: false
