views.view.related_event:
  expected_config: { }
  update_actions:
    delete:
      display:
        related_event_by_type:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        related_event_by_type:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
    change:
      display:
        related_event_by_type:
          display_title: 'By event type - on term page '
          position: 3
