user.role.anonymous:
  expected_config:
    label: Gast
  update_actions:
    change:
      label: 'Anonymous user'
user.role.authenticated:
  expected_config:
    label: 'Angemeldeter Benutzer'
  update_actions:
    change:
      label: 'Authenticated user'
