views.view.related_article:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            arguments:
              field_category_target_id:
    add:
      display:
        default:
          display_options:
            arguments:
              term_node_tid_depth:
                id: term_node_tid_depth
                table: node_field_data
                field: term_node_tid_depth
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                plugin_id: taxonomy_index_tid_depth
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: taxonomy_tid
                default_argument_options:
                  term_page: '1'
                  node: false
                  limit: false
                  vids: { }
                  anyall: ','
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: true
                validate:
                  type: 'entity:taxonomy_term'
                  fail: empty
                validate_options:
                  bundles:
                    category: category
                  access: false
                  operation: view
                  multiple: 0
                break_phrase: false
                depth: 1
                use_taxonomy_term_path: false

views.view.related_date:
  expected_config: {  }
  update_actions:
    delete:
      display:
        by_term:
          display_options:
            arguments:
              field_category_target_id:
    add:
      display:
        by_term:
          display_options:
            arguments:
              term_node_tid_depth:
                id: term_node_tid_depth
                table: node_field_data
                field: term_node_tid_depth
                relationship: field_event_description
                group_type: group
                admin_label: ''
                entity_type: node
                plugin_id: taxonomy_index_tid_depth
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: taxonomy_tid
                default_argument_options:
                  term_page: '1'
                  node: false
                  limit: false
                  vids: {  }
                  anyall: ','
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: true
                validate:
                  type: 'entity:taxonomy_term'
                  fail: 'not found'
                validate_options:
                  bundles:
                    category: category
                  access: false
                  operation: view
                  multiple: 0
                break_phrase: false
                depth: 1
                use_taxonomy_term_path: false

views.view.related_profile:
  expected_config: {  }
  update_actions:
    delete:
      display:
        related_profile_term_artist:
          display_options:
            arguments:
              field_category_target_id:
        related_profile_term_organizer:
          display_options:
            arguments:
              field_category_target_id:
    add:
      display:
        related_profile_term_artist:
          display_options:
            arguments:
              term_node_tid_depth:
                id: term_node_tid_depth
                table: node_field_data
                field: term_node_tid_depth
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                plugin_id: taxonomy_index_tid_depth
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: taxonomy_tid
                default_argument_options:
                  term_page: '1'
                  node: false
                  limit: false
                  vids: { }
                  anyall: ','
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: true
                validate:
                  type: 'entity:taxonomy_term'
                  fail: empty
                validate_options:
                  bundles:
                    category: category
                  access: false
                  operation: view
                  multiple: 0
                break_phrase: false
                depth: 1
                use_taxonomy_term_path: false
        related_profile_term_organizer:
          display_options:
            arguments:
              term_node_tid_depth:
                id: term_node_tid_depth
                table: node_field_data
                field: term_node_tid_depth
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                plugin_id: taxonomy_index_tid_depth
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: taxonomy_tid
                default_argument_options:
                  term_page: '1'
                  node: false
                  limit: false
                  vids: { }
                  anyall: ','
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: true
                validate:
                  type: 'entity:taxonomy_term'
                  fail: empty
                validate_options:
                  bundles:
                    category: category
                  access: false
                  operation: view
                  multiple: 0
                break_phrase: false
                depth: 1
                use_taxonomy_term_path: false
