__global_actions:
  import_configs:
    - field.storage.node.field_badges
    - field.field.node.profile.field_badges

views.view.related_profile:
  expected_config: {  }
  update_actions:
    add:
      display:
        profile_peers:
          id: profile_peers
          display_title: Peers
          display_plugin: block
          position: 9
          display_options:
            pager:
              type: infinite_scroll
              options:
                offset: 0
                items_per_page: 24
                total_pages: null
                id: 0
                tags:
                  next: ››
                  previous: ‹‹
                expose:
                  items_per_page: false
                  items_per_page_label: 'Items per page'
                  items_per_page_options: '5, 10, 25, 50'
                  items_per_page_options_all: false
                  items_per_page_options_all_label: '- All -'
                  offset: false
                  offset_label: Offset
                views_infinite_scroll:
                  button_text: 'Load More'
                  automatically_load_content: false
                  initially_load_all_pages: false
            exposed_form:
              type: basic
              options:
                submit_button: Apply
                reset_button: false
                reset_button_label: Reset
                exposed_sorts_label: 'Sort by'
                expose_sort_order: true
                sort_asc_label: Asc
                sort_desc_label: Desc
            empty: { }
            sorts:
              sticky:
                id: sticky
                table: node_field_data
                field: sticky
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                entity_field: sticky
                plugin_id: standard
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
              changed:
                id: changed
                table: node_field_data
                field: changed
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                entity_field: changed
                plugin_id: date
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
                granularity: minute
            filters:
              status:
                id: status
                table: node_field_data
                field: status
                entity_type: node
                entity_field: status
                plugin_id: boolean
                value: '1'
                group: 1
                expose:
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
              field_badges_value:
                id: field_badges_value
                table: node__field_badges
                field: field_badges_value
                relationship: none
                group_type: group
                admin_label: ''
                plugin_id: list_field
                operator: 'not empty'
                value:
                  all: all
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                reduce_duplicates: false
              type:
                id: type
                table: node_field_data
                field: type
                entity_type: node
                entity_field: type
                plugin_id: bundle
                value:
                  profile: profile
                group: 1
                expose:
                  operator_limit_selection: false
                  operator_list: { }
              default_langcode:
                id: default_langcode
                table: node_field_data
                field: default_langcode
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: node
                entity_field: default_langcode
                plugin_id: boolean
                operator: '='
                value: '1'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
            filter_groups:
              operator: AND
              groups:
                1: AND
            defaults:
              empty: false
              css_class: false
              pager: false
              exposed_form: false
              sorts: false
              filters: false
              filter_groups: false
            css_class: 'profiles grid-1 grid-2-m grid-row-gap-2'
            display_description: ''
            rendering_language: '***LANGUAGE_language_interface***'
            display_extenders: { }
          cache_metadata:
            max-age: -1
            contexts:
              - 'languages:language_interface'
              - url.query_args
              - 'user.node_grants:view'
              - user.permissions
            tags: { }

