__global_actions:
  import_configs:
    - field.storage.node.field_pricing_info
    - field.field.node.date.field_pricing_info

core.entity_form_display.node.date.bulk_edit:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.search_index:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.search_result:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.teaser_big:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.teaser_unified:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.compact:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true
core.entity_view_display.node.date.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_pricing_info: true

core.entity_form_display.node.date.default:
  expected_config: { }
  update_actions:
    add:
      content:
        field_pricing_info:
          region: content
          settings:
            placeholder: ''
            rows: 2
          third_party_settings:
            allowed_formats:
              hide_guidelines: '0'
              hide_help: '1'
          type: text_textarea
          weight: 11
      third_party_settings:
        field_group:
          group_tickets:
            children:
              - field_pricing_info
    change:
      content:
        field_pricing:
          third_party_settings:
            conditional_fields: {  }
        field_safety_info:
          settings:
            rows: 2
        field_ticketing:
          weight: 12
        path:
          weight: 6
        simple_sitemap:
          weight: 8
        sticky:
          weight: 5
        url_redirects:
          weight: 7

core.entity_view_display.node.date.full:
  expected_config: { }
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_alternative_dates:
            format_settings:
              required_fields: false
          group_gallery:
            format_settings:
              required_fields: false
          group_organizer:
            format_settings:
              required_fields: false
    add:
      content:
        field_pricing_info:
          label: visually_hidden
          region: content
          settings: {  }
          third_party_settings: {  }
          type: text_default
          weight: 9
      third_party_settings:
        field_group:
          group_location:
            children:
              - field_attendance_mode
              - field_location_virtual
              - extra_field_location_address_data
              - field_location
              - field_safety_info
            format_settings:
              classes: ''
              description: ''
              id: location
              open: true
              show_empty_fields: false
            format_type: details
            label: 'Event location'
            parent_name: ''
            region: content
            weight: 10
          group_tickets:
            children:
              - field_pricing_info
    change:
      content:
        extra_field_event_gallery:
          weight: 24
        field_accessibility:
          weight: 24
        field_ticketing:
          weight: 10
      third_party_settings:
        field_group:
          group_accessibility_information:
            format_settings:
              id: a11y
            weight: 13
          group_alternative_dates:
            format_settings:
              id: alternative-dates
            weight: 15
          group_cast:
            format_settings:
              id: featuring
            weight: 12
          group_dates_in_this_series_info:
            weight: 19
          group_gallery:
            format_settings:
              id: gallery
            weight: 16
          group_interact:
            format_settings:
              id: interact
          group_organizer:
            format_settings:
              id: organizer
            weight: 14
          group_part_of_event_series:
            format_settings:
              id: series
            weight: 11
          group_tagging:
            format_settings:
              id: focus
          group_tickets:
            format_settings:
              id: pricing
            weight: 9
