views.view.related_date:
  expected_config: { }
  update_actions:
    add:
      display:
        block_front_dates:
          display_options:
            defaults:
              empty: false
            empty:
              area:
                admin_label: ''
                content:
                  format: basic_html
                  value: 'It seems like there are currently no upcoming dates in the database.'
                empty: true
                field: area
                group_type: group
                id: area
                plugin_id: text
                relationship: none
                table: views
                tokenize: false
            rendering_language: '***LANGUAGE_language_interface***'
