field.field.node.article.field_sub_type:
  expected_config: { }
  update_actions:
    change:
      label: 'Article type'
      description: 'Optionally select an appropriate type. Leave empty when in doubt (or when none available). When set, this will override the column display in teasers.'

field.field.node.event.field_sub_type:
  expected_config: { }
  update_actions:
    change:
      label: 'Event type'
      description: 'Select the most appropriate type to give an orientation. Leave empty if none applies.'

field.field.node.location.field_sub_type:
  expected_config: { }
  update_actions:
    change:
      label: 'Location type'
      description: 'Select the most appropriate type to give an orientation. Leave empty if none applies.'

field.field.node.page.field_sub_type:
  expected_config: { }
  update_actions:
    change:
      label: 'Page type'
      description: 'Optionally select an appropriate type. Leave empty when in doubt (or when none available).'
