__global_actions:
  import_configs:
    - taxonomy.vocabulary.article_type
    - taxonomy.vocabulary.event_type
    - taxonomy.vocabulary.location_type
    - taxonomy.vocabulary.page_type
    - field.field.taxonomy_term.page_type.field_mood_image
    - field.field.taxonomy_term.page_type.field_related_article_view_ref
    - field.field.taxonomy_term.page_type.field_term_children_view_ref
    - field.field.taxonomy_term.location_type.field_term_children_view_ref
    - field.field.taxonomy_term.location_type.field_related_location_view_ref
    - field.field.taxonomy_term.location_type.field_mood_image
    - field.field.taxonomy_term.event_type.field_term_children_view_ref
    - field.field.taxonomy_term.event_type.field_related_event_view_ref
    - field.field.taxonomy_term.event_type.field_mood_image
    - field.field.taxonomy_term.article_type.field_mood_image
    - field.field.taxonomy_term.article_type.field_related_article_view_ref
    - field.field.taxonomy_term.article_type.field_term_children_view_ref
    - core.entity_form_display.taxonomy_term.article_type.default
    - core.entity_form_display.taxonomy_term.event_type.default
    - core.entity_form_display.taxonomy_term.location_type.default
    - core.entity_form_display.taxonomy_term.page_type.default
    - core.entity_view_display.taxonomy_term.article_type.default
    - core.entity_view_display.taxonomy_term.article_type.full
    - core.entity_view_display.taxonomy_term.article_type.teaser
    - core.entity_view_display.taxonomy_term.event_type.default
    - core.entity_view_display.taxonomy_term.event_type.full
    - core.entity_view_display.taxonomy_term.event_type.teaser
    - core.entity_view_display.taxonomy_term.location_type.default
    - core.entity_view_display.taxonomy_term.location_type.full
    - core.entity_view_display.taxonomy_term.location_type.teaser
    - core.entity_view_display.taxonomy_term.page_type.default
    - core.entity_view_display.taxonomy_term.page_type.full
    - core.entity_view_display.taxonomy_term.page_type.teaser
    - core.base_field_override.taxonomy_term.article_type.changed
    - core.base_field_override.taxonomy_term.article_type.metatag
    - core.base_field_override.taxonomy_term.event_type.changed
    - core.base_field_override.taxonomy_term.event_type.metatag
    - core.base_field_override.taxonomy_term.location_type.changed
    - core.base_field_override.taxonomy_term.location_type.metatag
    - core.base_field_override.taxonomy_term.page_type.changed
    - core.base_field_override.taxonomy_term.page_type.metatag
    - pathauto.pattern.article_types
    - pathauto.pattern.event_types
    - pathauto.pattern.event_types_de
    - pathauto.pattern.location_type
    - pathauto.pattern.location_type_de
    - pathauto.pattern.page_type
    - language.content_settings.taxonomy_term.article_type
    - language.content_settings.taxonomy_term.event_type
    - language.content_settings.taxonomy_term.location_type
    - language.content_settings.taxonomy_term.page_type
    - simple_sitemap.bundle_settings.default.taxonomy_term.article_type
    - simple_sitemap.bundle_settings.default.taxonomy_term.location_type
    - simple_sitemap.bundle_settings.default.taxonomy_term.page_type
    - views.view.related_pages
    - views.view.oc_frontpage
