core.entity_view_display.taxonomy_term.article_type.full:
  expected_config:
    third_party_settings:
      field_group:
        group_sub_categories:
          format_settings:
            open: false
            required_fields: false
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              required_fields: false
    change:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              open: true
core.entity_view_display.taxonomy_term.event_type.full:
  expected_config:
    third_party_settings:
      field_group:
        group_sub_catgories:
          format_settings:
            open: false
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_sub_catgories:
            format_settings:
              open: true
core.entity_view_display.taxonomy_term.location_type.full:
  expected_config:
    third_party_settings:
      field_group:
        group_sub_categories:
          format_settings:
            open: false
            required_fields: false
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              required_fields: false
    change:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              open: true
core.entity_view_display.taxonomy_term.page_type.full:
  expected_config:
    third_party_settings:
      field_group:
        group_sub_categories:
          format_settings:
            open: false
            required_fields: false
  update_actions:
    delete:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              required_fields: false
    change:
      third_party_settings:
        field_group:
          group_sub_categories:
            format_settings:
              open: true
