views.view.locations:
  expected_config:
    display:
      attachment_map:
        display_options:
          header: {  }
      default:
        display_options:
          pager:
            options:
              expose:
                items_per_page: false
                items_per_page_label: 'Items per page'
                items_per_page_options: '5, 10, 25, 50'
              items_per_page: 6
  update_actions:
    add:
      display:
        attachment_map:
          display_options:
            defaults:
              footer: false
            render_pager: true
    change:
      display:
        attachment_map:
          display_options:
            footer: {  }
            header:
              result:
                admin_label: ''
                content: '<div class="result-counter">Displaying <strong>@start - @end</strong> of <strong>@total</strong></div>'
                empty: false
                field: result
                group_type: group
                id: result
                plugin_id: result
                relationship: none
                table: views
        default:
          display_options:
            pager:
              options:
                expose:
                  items_per_page: true
                  items_per_page_label: No./page
                  items_per_page_options: '24, 60, 120, 240'
                items_per_page: 60
views.view.related_date:
  expected_config:
    display:
      upcoming_dates:
        display_options:
          pager:
            options:
              expose:
                items_per_page: false
                items_per_page_label: 'Items per page'
                items_per_page_options: '5, 10, 25, 50'
              items_per_page: 12
      upcoming_dates_map:
        display_options:
          render_pager: false
  update_actions:
    add:
      display:
        upcoming_dates:
          display_options:
            exposed_form:
              options:
                bef:
                  pager:
                    advanced:
                      is_secondary: true
                    plugin_id: default
        upcoming_dates_map:
          display_options:
            defaults:
              footer: false
              header: false
            footer: {  }
            header:
              result:
                admin_label: ''
                content: '<div class="result-counter">Displaying <strong>@start - @end</strong> of <strong>@total</strong></div>'
                empty: false
                field: result
                group_type: group
                id: result
                plugin_id: result
                relationship: none
                table: views
    change:
      display:
        upcoming_dates:
          display_options:
            pager:
              options:
                expose:
                  items_per_page: true
                  items_per_page_label: No./page
                  items_per_page_options: '24, 60, 120, 240'
                items_per_page: 60
        upcoming_dates_map:
          display_options:
            render_pager: true
