__global_actions:
  install_modules:
    - openculturas_media
  import_configs:
    - core.entity_view_mode.node.teaser_big
    - core.entity_view_display.node.article.teaser_big
    - core.entity_view_display.node.date.teaser_big
    - core.entity_view_display.node.event.teaser_big
    - core.entity_view_display.node.location.teaser_big
    - core.entity_view_display.node.page.teaser_big
    - core.entity_view_display.node.profile.teaser_big
