views.view.related_date:
  expected_config:
    display:
      default:
        display_options:
          filters:
            field_date_end_value:
              value:
                granularity: day
      related_date_organizer:
        display_options:
          filters:
            field_date_end_value:
              value:
                granularity: day
            field_date_value:
              value:
                granularity: day
      upcoming_dates:
        display_options:
          filters:
            field_date_end_value_1:
              value:
                granularity: day
            field_date_value:
              value:
                granularity: day
      upcoming_dates_map:
        display_options:
          filters:
            field_date_end_value_1:
              value:
                granularity: day
            field_date_value:
              value:
                granularity: day
  update_actions:
    change:
      display:
        default:
          display_options:
            filters:
              field_date_end_value:
                value:
                  granularity: hour
        related_date_organizer:
          display_options:
            filters:
              field_date_end_value:
                value:
                  granularity: hour
              field_date_value:
                value:
                  granularity: hour
        upcoming_dates:
          display_options:
            filters:
              field_date_end_value_1:
                value:
                  granularity: hour
              field_date_value:
                value:
                  granularity: hour
        upcoming_dates_map:
          display_options:
            filters:
              field_date_end_value_1:
                value:
                  granularity: hour
              field_date_value:
                value:
                  granularity: hour
