__global_actions:
  import_configs:
    - facets.facet_source.search_api__views_block__search__search_input
    - facets.facet_source.search_api__views_page__search__search_page
    - facets.facet.sub_type_taxonomy_term_name
    - block.block.typetaxonomytermname

block.block.a11y_features:
  expected_config: { }
  update_actions:
    change:
      settings:
        label_display: '0'
      weight: -9
block.block.call_to_action:
  expected_config: { }
  update_actions:
    change:
      weight: -8
block.block.category:
  expected_config: { }
  update_actions:
    change:
      settings:
        label_display: '0'
      weight: -13
block.block.openculturas_base_content:
  expected_config: { }
  update_actions:
    change:
      weight: 0
block.block.userlogin:
  expected_config: { }
  update_actions:
    change:
      weight: -3
facets.facet.a11y_features:
  expected_config: { }
  update_actions:
    add:
      processor_configs:
        hierarchy_processor:
          processor_id: hierarchy_processor
          settings: {  }
          weights:
            build: 100
    change:
      name: Accessibility
      processor_configs:
        active_widget_order:
          settings:
            sort: ASC
      show_title: true
      widget:
        config:
          hide_reset_when_no_selection: true
          show_reset_link: true
facets.facet.category_taxonomy_term_name:
  expected_config: { }
  update_actions:
    delete:
      widget:
        config:
          default_option_label: Choose
    add:
      processor_configs:
        translate_entity:
          processor_id: translate_entity
          settings: {  }
          weights:
            build: 5
    change:
      enable_parent_when_child_gets_disabled: false
      expand_hierarchy: true
      field_identifier: field_category
      name: Focus
      processor_configs:
        active_widget_order:
          settings:
            sort: ASC
      show_only_one_result: false
      show_title: true
      weight: -1
      widget:
        config:
          hide_reset_when_no_selection: true
          reset_text: 'Show all'
          show_numbers: true
          show_reset_link: true
          soft_limit: 10
          soft_limit_settings:
            show_less_label: 'Show less'
            show_more_label: 'Show more'
        type: links
search_api.index.content:
  expected_config: { }
  update_actions:
    delete:
      field_settings:
        rendered_item:
          configuration:
            view_mode:
              'entity:node':
                date: search_index
      processor_settings:
        html_filter:
    add:
      field_settings:
        category_name:
          boost: !!float 2
        field_category:
          datasource_id: 'entity:node'
          dependencies:
            config:
              - field.storage.node.field_category
          label: 'Focus (facet)'
          property_path: field_category
          type: integer
        field_sub_type:
          boost: !!float 2
          datasource_id: 'entity:node'
          dependencies:
            config:
              - field.storage.node.field_sub_type
            module:
              - taxonomy
          label: 'Type Taxonomy (fulltext)'
          property_path: 'field_sub_type:entity:name'
          type: string
        field_sub_type_1:
          datasource_id: 'entity:node'
          dependencies:
            config:
              - field.storage.node.field_sub_type
          label: 'Type (facet)'
          property_path: field_sub_type
          type: integer
      processor_settings:
        ignorecase:
          fields:
            - category_name
            - field_a11y_features
            - field_sub_type
            - field_subtitle
            - title
        reverse_entity_references: {  }
        transliteration:
          fields:
            - category_name
            - field_a11y_features
            - field_sub_type
            - field_subtitle
            - title
        type_boost:
          boosts:
            'entity:node':
              bundle_boosts:
                faq: 0.5
                page: 0.3
              datasource_boost: !!float 1
          weights:
            preprocess_index: 0
    change:
      field_settings:
        category_name:
          label: 'Focus Taxonomy (fulltext)'
        field_subtitle:
          boost: !!float 13
        title:
          boost: !!float 21
      processor_settings:
        ignorecase:
          all_fields: true
        transliteration:
          all_fields: true

views.view.media_library:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            pager:
              options:
                quantity: 9
                tags:
                  first: '« First'
                  last: 'Last »'
    change:
      display:
        default:
          display_options:
            pager:
              type: full
views.view.search:
  expected_config: { }
  update_actions:
    delete:
      display:
        default:
          cache_metadata:
            contexts:
              - 'languages:language_content'
          display_options:
            fields:
              category_name:
            row:
              options:
                view_modes:
                  'entity:node':
                    date: teaser
        search_input:
          cache_metadata:
            contexts:
              - 'languages:language_content'
        search_page:
          cache_metadata:
            contexts:
              - 'languages:language_content'
    add:
      display:
        default:
          display_options:
            css_class: form--compact
            filters:
              search_api_fulltext:
                fields:
                  - field_subtitle
                  - title
              search_api_language:
                admin_label: ''
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: search_api_language
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: search_api_language
                is_grouped: false
                operator: in
                plugin_id: search_api_language
                relationship: none
                table: search_api_index_content
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
            style:
              options:
                default_row_class: true
                row_class: ''
                uses_fields: false
            use_ajax: true
        search_input:
          display_options:
            defaults:
              use_ajax: false
            filters:
              search_api_fulltext:
                fields:
                  - field_subtitle
                  - title
              search_api_language:
                admin_label: ''
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: search_api_language
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: search_api_language
                is_grouped: false
                operator: in
                plugin_id: search_api_language
                relationship: none
                table: search_api_index_content
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
            use_ajax: false
        search_page:
          display_options:
            defaults:
              header: true
              use_ajax: true
    change:
      display:
        default:
          display_options:
            fields: {  }
            filter_groups:
              groups: {  }
              operator: AND
            filters:
              search_api_fulltext:
                expose:
                  required: true
                plugin_id: views_autocomplete_filters_search_api_fulltext
            pager:
              options:
                items_per_page: 24
            sorts:
              changed:
                expose:
                  field_identifier: ''
                  label: ''
              search_api_relevance:
                expose:
                  field_identifier: ''
                  label: ''
        search_page:
          display_options:
            exposed_block: true
