block.block.bookmarkflagicon:
  expected_config: {  }
  update_actions:
    change:
      status: true
      region: header_intro

flag.flag.recommendation_node:
  expected_config: {  }
  update_actions:
    change:
      unflag_short: 'Edit recommendation'
      unflag_long: 'Modify or remove'

core.entity_view_display.node.article.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        body:
          weight: 5
        field_author:
          weight: 7
        field_content_paragraphs:
          weight: 6
        field_date_published:
          weight: 4
      third_party_settings:
        field_group:
          group_interact:
            weight: 8
          group_workflow:
            weight: 0
core.entity_view_display.node.date.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        extra_field_event_body:
          weight: 5
        field_body_addon:
          weight: 4
        field_date:
          weight: 3
        field_event_description:
          weight: 6
        field_event_status:
          weight: 1
        field_premiere:
          weight: 2
      third_party_settings:
        field_group:
          group_interact:
            weight: 7
core.entity_view_display.node.event.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        body:
          weight: 2
        extra_field_social_media_buttons:
          weight: 3
        field_status:
          weight: 1
        flag_claim_ownership:
          weight: 4
        flag_report_abuse:
          weight: 5
      third_party_settings:
        field_group:
          group_interact:
            weight: 3
          group_sponsors:
            weight: 15
          group_workflow:
            weight: 0
core.entity_view_display.node.location.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        body:
          weight: 3
        extra_field_social_media_buttons:
          weight: 3
        field_logo:
          weight: 2
        field_portrait:
          weight: 1
        field_started:
          weight: 4
        flag_claim_ownership:
          weight: 4
        flag_report_abuse:
          weight: 5
      third_party_settings:
        field_group:
          group_interact:
            weight: 5
core.entity_view_display.node.page.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        content_moderation_control:
          weight: 0
        field_mood_image:
          weight: 1
        field_subtitle:
          weight: 2
      third_party_settings:
        field_group:
          group_interact:
            weight: 5
          group_sponsors:
            weight: 6
core.entity_view_display.node.profile.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        body:
          weight: 2
        extra_field_social_media_buttons:
          weight: 3
        field_logo:
          weight: 1
        field_started:
          weight: 3
        flag_claim_ownership:
          weight: 4
        flag_report_abuse:
          weight: 5
      third_party_settings:
        field_group:
          group_interact:
            weight: 4
core.entity_view_display.taxonomy_term.article_type.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
      third_party_settings:
        field_group:
          group_articles:
            weight: 2
          group_interact:
            weight: 3
          group_sub_categories:
            weight: 1
core.entity_view_display.taxonomy_term.category.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
        field_related_artist_view_ref:
          weight: 1
      third_party_settings:
        field_group:
          group_artists:
            weight: 5
          group_interact:
            weight: 8
          group_locations:
            weight: 4
          group_magazine:
            weight: 7
          group_organizer:
            weight: 6
          group_sub_categories:
            weight: 1
          group_upcoming_dates:
            weight: 2
          group_upcoming_events:
            weight: 3
core.entity_view_display.taxonomy_term.column.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
        field_related_article_view_ref:
          weight: 2
      third_party_settings:
        field_group:
          group_interact:
            weight: 3
          group_sub_categories:
            weight: 1
core.entity_view_display.taxonomy_term.event_type.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
      third_party_settings:
        field_group:
          group_events:
            weight: 2
          group_interact:
            weight: 3
          group_sub_catgories:
            weight: 1
core.entity_view_display.taxonomy_term.location_type.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
      third_party_settings:
        field_group:
          group_interact:
            weight: 3
          group_locations:
            weight: 2
          group_sub_categories:
            weight: 1
core.entity_view_display.taxonomy_term.page_type.full:
  expected_config: {  }
  update_actions:
    change:
      content:
        description:
          weight: 0
      third_party_settings:
        field_group:
          group_interact:
            weight: 3
          group_pages:
            weight: 2
          group_sub_categories:
            weight: 1

