views.view.related_date:
  expected_config: {  }
  update_actions:
    add:
      display:
        upcoming_dates:
          display_options:
            exposed_form:
              options:
                bef:
                  filter:
                    field_sub_type_target_id:
                      advanced:
                        collapsible: false
                        is_secondary: true
                        rewrite:
                          filter_rewrite_values: ''
                        sort_options: false
                      plugin_id: default
            filters:
              field_sub_type_target_id:
                admin_label: 'Event type'
                error_message: true
                expose:
                  description: ''
                  identifier: event_type
                  label: Type
                  multiple: false
                  operator: field_sub_type_target_id_op
                  operator_id: field_sub_type_target_id_op
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: true
                field: field_sub_type_target_id
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                hierarchy: true
                id: field_sub_type_target_id
                is_grouped: false
                limit: true
                operator: or
                plugin_id: taxonomy_index_tid
                reduce_duplicates: false
                relationship: field_event_description
                table: node__field_sub_type
                type: select
                value: {  }
                vid: event_type
        upcoming_dates_map:
          display_options:
            filters:
              field_sub_type_target_id:
                admin_label: 'Event type'
                error_message: true
                expose:
                  description: ''
                  identifier: event_type
                  label: 'Event type'
                  multiple: false
                  operator: field_sub_type_target_id_op
                  operator_id: field_sub_type_target_id_op
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: true
                field: field_sub_type_target_id
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                hierarchy: true
                id: field_sub_type_target_id
                is_grouped: false
                limit: true
                operator: or
                plugin_id: taxonomy_index_tid
                reduce_duplicates: false
                relationship: field_event_description
                table: node__field_sub_type
                type: select
                value: {  }
                vid: event_type
