__global_actions:
  import_configs:
    - oembed_providers.bucket.video

cookies.cookies_service.video:
  expected_config:
    label: 'Video provided by YouTube, Vimeo'
    placeholderAcceptText: 'Only accept video provided by youtube, vimeo cookies'
    placeholderMainText: 'This content is blocked because video provided by youtube, vimeo cookies have not been accepted.'
  update_actions:
    change:
      label: 'External video'
      placeholderAcceptText: 'Only accept video cookies'
      placeholderMainText: 'This content is blocked because external video cookies have not been accepted.'
