__global_actions:
  import_configs:
    - core.base_field_override.paragraph.teaser_external.created
    - core.base_field_override.paragraph.teaser_external.status
    - core.base_field_override.paragraph.teaser_node.created
    - core.base_field_override.paragraph.teaser_node.status
    - core.base_field_override.paragraph.teaser_term.created
    - core.base_field_override.paragraph.teaser_term.status
    - core.base_field_override.paragraph.teaser_wrapper.created
    - core.base_field_override.paragraph.teaser_wrapper.status
    - language.content_settings.paragraph.teaser_external
    - language.content_settings.paragraph.teaser_node
    - language.content_settings.paragraph.teaser_term
    - language.content_settings.paragraph.teaser_wrapper

field.field.paragraph.teaser_external.field_url_single_value:
  expected_config: { }
  update_actions:
    change:
      translatable: true
