views.view.content_recent:
  expected_config:
    status: true
  update_actions:
    change:
      status: false

views.view.who_s_new:
  expected_config:
    status: true
  update_actions:
    change:
      status: false

views.view.who_s_online:
  expected_config:
    status: true
  update_actions:
    change:
      status: false
