condition.plugin.user_page:
  type: condition.plugin
  mapping:
    enabled:
      type: boolean
    only_for_owner:
      type: boolean


openculturas_custom.eca_notification_recipient.*:
  type: config_entity
  label: ECA notification recipient
  mapping:
    id:
      type: string
      label: ID
    label:
      type: string
      label: Label
    eca_model:
      type: sequence
      sequence:
        type: boolean
    preferred_langcode:
      type: string
